#! /Library/Frameworks/Python.framework/Versions/3.7/bin/python3

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    Red = '\033[0;31;40m'
    RedUnderline = '\033[1;31;40m'

def TextColor(string,color='stock'):
    if color == 'stock':
        Format = '\033[0m'
    elif color == 'red':
        Format = '\033[0;31;40m'
    return (Format + string + bcolors.ENDC)

print (bcolors.RedUnderline + 'This is a string' + bcolors.ENDC + '\nthis is a exit string')

print (TextColor('test string','red'))
